preprocess:
  test_size: 0.2
  random_state: 42
  scaling: standard   # options: standard, minmax

train:
  model_type: logistic_regression   # could be logistic_regression, random_forest, xgboost
  logistic_regression:
    C: 1.0
    max_iter: 1000
  random_forest:
    n_estimators: 100
    max_depth: 10
    random_state: 42
  xgboost:
    n_estimators: 200
    learning_rate: 0.1
    max_depth: 6
    random_state: 42

evaluate:
  metrics:
    - accuracy
    - precision
    - recall
    - f1
    - roc_auc
